### ISSUE TITLE
Deriving `Config` for enums

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/confique#3]
(Issue moved from [here](https://github.com/LukasKalbertodt/confique/issues/1#issuecomment-1250169754) for better discussion)

@amkartashov wrote:

> What about allowing to derive Config for enums? I started using your library in my project and have oneof fields described by enums. I parse it with serde fow now, so it's a mixed approach.

**Comment by LukasKalbertodt** [comment]
@amkartashov could you describe your use case in more detail? Maybe some example code how you wish `confique` would work?

**Comment by amkartashov** [comment]
Thanks @LukasKalbertodt 
My usecase is to support mutually exclusive sections in config file. I'm writing app which can use different backend types, so it can store blobs on a filesystem or in KV storage or something else.

In config it looks like this (filesystem as backend):

```yaml
backend:
  actions:
    module: fs
    options:
      path: /tmp/cache/ac
  blobs:
    module: fs
    options:
      path: /tmp/cache/cas
      max_chunk_size: 10000000
```

or like this (GRPC service as backend for actions, TiKV as backend for blobs)

```yaml
backend:
  actions:
    module: grpc
    options:
      url: grpc://localhost:8980
  blobs:
    module: tikv
    options:
      db_url:  ...
      max_chunk_size: 10000000
```

As of now, I use serde to parse config file:

```rust
#[derive(Debug, Deserialize, Config, Clone)]
pub struct Conf {
...
    #[config(nested)]
    pub backend: BackendConf,
}

#[derive(Debug, Deserialize, Config, Clone)]
pub struct BackendConf {
...
    pub actions: Option<ActionStorageConf>,
    pub blobs: Option<BlobStorageConf>,
}



#[derive(Debug, Deserialize, Clone)]
#[serde(tag = "module", content = "options")]
pub enum ActionStorageConf {
    #[serde(alias = "fs")]
    FS(FsActionStorageConf),
   ...
}

#[derive(Debug, Deserialize, Clone)]
#[serde(tag = "module", content = "options")]
pub enum BlobStorageConf {
    #[serde(alias = "fs")]
    FS(FsBlobStorageConf),
    ...
}

#[derive(Debug, Deserialize, Clone)]
pub struct FsActionStorageConf {
    pub path: PathBuf,
}

#[derive(Debug, Deserialize, Clone)]
pub struct FsBlobStorageConf {
    pub path: PathBuf,
    #[serde(default = "default_fs_blob_max_chunk_size")]
    pub max_chunk_size: usize,
}
```
